name: example_map_polyline
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter:
    #path: ../google_maps_flutter/google_maps_flutter
    git:
      url: https://github.com/cylyl/plugins.git
      path: packages/google_maps_flutter/google_maps_flutter
      ref: fad13b633cbcda82848fd23de6901b8e46619c1c

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_map_polyline:
    path: ../

flutter:

  uses-material-design: true
