name: google_map_polyline
description: Gives the polyline coordinates to set polylines in Google Map.
version: 0.2.0+1
author: Shakir Samoon <shakirsamoon@gmail.com>
homepage: https://github.com/Shark01/google_map_polyline

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: 
    #path: ../google_maps_flutter/google_maps_flutter
    git:
      url: https://github.com/cylyl/plugins.git
      path: packages/google_maps_flutter/google_maps_flutter
      ref: fad13b633cbcda82848fd23de6901b8e46619c1c

  dio: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
